### PR TITLE
Catalan translation of menus.

### PR DESCRIPTION
**Pull request by wagafo**
Please my contribution: Translation of the menus to Catalan.

### CODE REVIEW

**Comment by seankross** [comment]
Hey @wagafo this looks great, thank you so much! Is it okay if I merge it?

**Comment by wagafo** [comment]
Thanks @seankross , please merge it!

**Comment by wagafo** [comment]
Do I have to also check the R files in swirl to add the Catalan language or are you going do to it?

**Comment by seankross** [comment]
Sorry for the delay with this PR but it looks great! Thanks so much!

**Comment by wagafo** [comment]
Thanks a lot to you for your work,
Walter

**Pull request merged**
