### PR TITLE
Update spanish.yaml

### PR DESCRIPTION
**Pull request by dhduncan**
Finished the non-Coursera dialogues, certainly with errors o some clunky translations.

### CODE REVIEW

**Comment by seankross** [comment]
Thank you!

**Comment by dhduncan** [comment]
Hi Sean,

I just realised that I don't know how the spanish.yaml file can be put into
service. Do you run tests on it before anything else happens?

regards,

David

**Comment by seankross** [comment]
Hi David, 

I just saw your second message. A development version of swirl that uses the translations should be released by the end of this week.

Sean

**Comment by dhduncan** [comment]
fantastic news Sean!

**Pull request merged**
